### PR TITLE
Lint test

### PR DESCRIPTION
**Pull request by maxired**
Hi, 

following PR #189 ,

here is the same stuff but for tests.

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@maxired You might need to rerun lint as that's what failed.

**Comment by maxired** [comment]
@mcdonnelldean , thanks for feedback, and sorry about that ;)

**Comment by mcdonnelldean** [comment]
@maxired No hassle :D LGTM now :D @geek can you confirm?

**Comment by geek** [comment]
@maxired well done

**Pull request merged**
